# name: bioimage_embed
channels:
  # - bioconda
  - pytorch
  - conda-forge
  # - defaults
  - torch
dependencies:
  - cudatoolkit-dev=10
  - python=3.9
  - mamba
  - poetry
  - gcc
  - libgcc
  - pytorch
  - pip
  - pip:
    - -e .
    - nonechucks
