name: base
channels:
  - bioconda
  - pytorch
  - idr
  - ome
  - conda-forge
  - defaults
  - torch
dependencies:
  - cudatoolkit=10.2
  - python=3.9
  - pytest
  - poetry
  - gcc
  - tensorboard
  - umap-learn
  - jupyter
  - pip
  - black
  - autopep8
  - pytorch
  - pytorch-lightning
  - pytorch-model-summary
  - pyro-ppl
  - matplotlib
  - torchvision
  - gsutil
  - pip:
    - -e .
    - nonechucks
