# name: torch
channels:
  - bioconda
  - pytorch
  - idr
  - ome
  - conda-forge
  # - defaults
  - torch
dependencies:
  - cudatoolkit=10.2
  - python=3.9
  - mamba
  - conda
  - pytest
  - poetry
  - gcc
  - tensorboard
  - umap-learn
  - jupyter
  - black
  - autopep8
  - pytorch
  - pytorch-lightning
  - pytorch-model-summary
  - pyro-ppl
  - matplotlib
  - torchvision
  - gsutil
  - pip
  - pip:
    - .
    - nonechucks
