#name: shapeembed
channels:
- conda-forge
#- defaults
- torch
- bioconda
dependencies:
- cudatoolkit-dev=10
- python=3.9
- mamba
- poetry
- gcc
- libgcc
- pytorch
- wandb
- pillow=9.5.0
- pip
- conda-forge::opencv
- pip:
  - -e .
