# model_name: VQVAE

# model:
_target_: pythae.models.VQVAE
# model_config: $(model.model_config)
encoder: 
  _target_: pythae.models.nn.benchmarks.celeba.Encoder_ResNet_VQVAE_CELEBA
  args: ${pythae.model_config}
decoder:
  _target_: pythae.models.nn.benchmarks.celeba.Decoder_ResNet_VQVAE_CELEBA
  args: ${pythae.model_config}

model_config:
  _target_: pythae.models.VQVAEConfig
  _convert_: all
  input_dim: ${model.input_dim}
  latent_dim: ${model.latent_dim}
