 # _target_: timm.optim.optimizer
opt: LAMB
lr: 1.0e-3 
weight_decay: 0.0001
momentum: 0.9
# scheduler:
# _target_: timm.scheduler.scheduler
sched: cosine
min_lr: 1.0e-6
warmup_epochs: 5
warmup_lr: 1.0e-6
cooldown_epochs: 10
t_max: 50
cycle_momentum: false
epochs: ${trainer.max_epochs}