defaults:
  - _self_
  - trainer: default.yaml
  - pythae: default.yaml
  # - optimizer: default.yaml
  # - scheulder: default.yaml
  - timm: default.yaml
  - augmentations: default.yaml
  # - dataset: default.yaml
  - dataloader: default.yaml
  - paths: default.yaml
  - lightning: default.yaml
  - bio_vae: default.yaml
  - logger: default.yaml
  - checkpoints: default.yaml

version_base: 2.0

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# name of the run, accessed by loggers
name: null

trainer:
  accelerator: "gpu"
  devices: "auto"
  gradient_clip_val: 1
  accumulate_grad_batches: 16
  min_epochs: 0
  max_epochs: 200
  strategy: "ddp"
  profiler: null
  fast_dev_run: False

dataset:
  name: "ivy_gap"
  # dir: "data"
  train_dataset_glob: ${paths.data_dir}/${dataset.name}/random/*png
  crop_size:
    - 128
    - 128

dataloader:
  batch_size: 32
  num_workers: 8
  pin_memory: false
  shuffle: true
  persistent_workers: true


timm:
  opt: LAMB
  lr: 1.0e-3 
  weight_decay: 0.0001
  momentum: 0.9
  sched: cosine
  min_lr: 1.0e-6
  warmup_epochs: 5
  warmup_lr: 1.0e-6
  cooldown_epochs: 10
  t_max: 50
  cycle_momentum: false

model:
  name: "VQVAE"
  input_dim: [3, 128, 128]
  latent_dim: 64

pythae:
  encoder:
    pythae.models.nn.benchmarks.celeba.Encoder_ResNet_VQVAE_CELEBA
    # _target_: Encoder_ResNet_VQVAE_CELEBA
  decoder: pythae.models.nn.benchmarks.celeba.Decoder_ResNet_VQVAE_CELEBA
  model_config:
    _target_: pythae.models.VQVAEConfig

albumentations:
  __version__: 1.3.0
  transform:
    __class_fullname__: Compose
    additional_targets: {}
    bbox_params: null
    keypoint_params: null
    p: 1.0
    transforms:
      - __class_fullname__: OneOf
        p: 0.5
        transforms:
          - __class_fullname__: HorizontalFlip
            always_apply: false
            p: 0.5
          - __class_fullname__: VerticalFlip
            always_apply: false
            p: 0.5
      - __class_fullname__: RandomResizedCrop
        always_apply: false
        height: ${dataset.crop_size[0]}
        p: 1
        width: ${dataset.crop_size[1]}
        scale:
          - 1.0
          - 1.0
      - __class_fullname__: Rotate
        always_apply: false
        border_mode: 4
        crop_border: false
        interpolation: 1
        limit:
          - -45
          - 45
        mask_value: null
        p: 0.5
        rotate_method: largest_box
        value: null
      - __class_fullname__: RandomGamma
        always_apply: false
        eps: null
        gamma_limit:
          - 80
          - 120
        p: 0.5
      - __class_fullname__: ElasticTransform
        alpha: 1
        alpha_affine: 50
        always_apply: false
        approximate: false
        border_mode: 4
        interpolation: 1
        mask_value: null
        p: 0.5
        same_dxdy: false
        sigma: 50
        value: null
      - __class_fullname__: GaussNoise
        always_apply: false
        mean: 0
        p: 0.5
        per_channel: true
        var_limit:
          - 10.0
          - 50.0
      - __class_fullname__: Normalize
        always_apply: true
        p: 1.0
      - __class_fullname__: ToTensorV2
        always_apply: true
        p: 1.0
        transpose_mask: false
