dataset: "ivy_gap"
data_dir: "data"
train_dataset_glob: f"{data_dir}/{dataset}/random/*png"

optimizer_params:
  opt: LAMB
  lr: 0.001
  weight_decay: 0.0001
  momentum: 0.9

lr_scheduler_params:
  sched: cosine
  min_lr: 1.0e-6
  warmup_epochs: 5
  warmup_lr: 1.0e-6
  cooldown_epochs: 10
  t_max: 50
  cycle_momentum: false

albumentations:
  __version__: 1.3.0
  transform:
    __class_fullname__: Compose
    additional_targets: {}
    bbox_params: null
    keypoint_params: null
    p: 1.0
    transforms:
    - __class_fullname__: OneOf
      p: 0.5
      transforms:
      - __class_fullname__: HorizontalFlip
        always_apply: false
        p: 0.5
      - __class_fullname__: VerticalFlip
        always_apply: false
        p: 0.5
    - __class_fullname__: Rotate
      always_apply: false
      border_mode: 4
      crop_border: false
      interpolation: 1
      limit:
      - -45
      - 45
      mask_value: null
      p: 0.5
      rotate_method: largest_box
      value: null
    - __class_fullname__: RandomGamma
      always_apply: false
      eps: null
      gamma_limit:
      - 80
      - 120
      p: 0.5
    - __class_fullname__: ElasticTransform
      alpha: 1
      alpha_affine: 50
      always_apply: false
      approximate: false
      border_mode: 4
      interpolation: 1
      mask_value: null
      p: 0.5
      same_dxdy: false
      sigma: 50
      value: null
    - __class_fullname__: GaussNoise
      always_apply: false
      mean: 0
      p: 0.5
      per_channel: true
      var_limit:
      - 10.0
      - 50.0
    - __class_fullname__: RandomCrop
      always_apply: false
      height: 128
      p: 1
      width: 128
    - __class_fullname__: RandomBrightnessContrast
      always_apply: false
      brightness_by_max: true
      brightness_limit:
      - -0.2
      - 0.2
      contrast_limit:
      - -0.2
      - 0.2
      p: 0.5
    - __class_fullname__: Normalize
      always_apply: false
      max_pixel_value: 255.0
      mean:
      - 0.485
      - 0.456
      - 0.406
      p: 1.0
      std:
      - 0.229
      - 0.224
      - 0.225
