_target_: pytorch_lightning.Trainer

accelerator: "gpu"
devices: "1"
# weights_summary: null
# progress_bar_refresh_rate: 5
# resume_from_checkpoint: null

logger: ${logger}
gradient_clip_val: 1
enable_checkpointing: True
accumulate_grad_batches: 4
callbacks:
  - ${checkpoints}
min_epochs: 50
max_epochs: 200
precision: 32