name: conda
on: [push]
jobs:
  constructor:
    name: conda build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      matrix:
        # os: [ubuntu, windows, macos]
        os: [ubuntu]
        python-version: ["3.9"]
        include:
        - os: ubuntu
          shell: bash -l {0}
          # - os: windows
          #   shell: cmd /C call {0}
          # - os: macos
          #   shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.dev.yml
        miniforge-variant: Mambaforge
        miniforge-version: latest
        mamba-version: "*"
        use-mamba: true
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: |
        make test
