# https://github.com/marketplace/actions/install-poetry-action
name: test

on: [pull_request,push]

jobs:
  test:
    # TODO how do I change the shell to bash here
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      # - name: Set up python
      #   id: setup-python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
      # - name: Install Poetry
      #   uses: snok/install-poetry@v1
      #   with:
      #     virtualenvs-create: true
      #     virtualenvs-in-project: true
      #     installer-parallel: true
      - name: poetry env
        run: poetry env use python
      - name: Poetry lock
        run: poetry lock     
      - name: Install library
        run: poetry install --no-interaction
      # - name: Run tests
      #   run: |
      #     source .venv/bin/activate
      #     pytest tests/