version: '3.8'
services:
  bioimage_embed:
    image: europe-west2-docker.pkg.dev/prj-ext-dev-mlops-bia-363210/q-embl-vq-vae/bioimage_embed:sakshi_scale_hpt_latest
    volumes:
      - .:/app
    # command: ["python", "/app/save_model.py"]
    entrypoint: []
    command: ["tail", "-f", "/dev/null"]
    environment:
      PYTHONPATH: "${PYTHONPATH}:/bioimage_embed_training"
